//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace STLx.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class WithBankAccount
    {
        public string Iqama { get; set; }
        public string BatchNo { get; set; }
        public string Name { get; set; }
        public string BankCode { get; set; }
        public string BankAccountNo { get; set; }
        public string Project { get; set; }
        public string EmployeeAddress1 { get; set; }
        public string EmployeeAddress2 { get; set; }
        public string EmployeeAddress3 { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<bool> IsDelete { get; set; }
    }
}
